# Generated by Django 3.1.5 on 2021-01-29 18:41

import board.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': '"catalog"."category"',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': '"catalog"."tags"',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='board.category', verbose_name='Основная категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table': '"catalog"."subcategory"',
            },
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер объявления')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Текущая цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Прошлая цена')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления')),
                ('upper_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата поднятия')),
                ('published', models.BooleanField(default=False, verbose_name='Статус объявления')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Дополнительное описание')),
                ('subcategories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='board.subcategory', verbose_name='Подкатегории')),
                ('tags', models.ManyToManyField(to='board.Tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': '"catalog"."board_item"',
            },
        ),
        migrations.CreateModel(
            name='BoardImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=board.helpers.get_upload_dir)),
                ('board_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.boarditem', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': '"catalog"."board_images"',
            },
        ),
    ]
