# Generated by Django 3.1.5 on 2021-02-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210208_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='board.category', verbose_name='Категории'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
